### PR TITLE
Force all left hand side boxes the same width.

### LINKED ISSUE #303: macOS 10.13: vertical gauges on main screen render incorrectly
This is likely a wxWidgets issue as it works fine on 10.13. See https://github.com/wxWidgets/wxWidgets/issues/22975 for more details. I'm creating an issue here so that we can track it if/when it's fixed upstream.

### LINKED ISSUE #610: 1.9.5 left side of main window widgets vanish when resizing main window height, this did not happen in b5d73 before release.
A bug was introduced just before release of 1.9.5 that breaks the re-arrangement of the widgets on the left side of the screen.
They are removed from view so that stats can not be monitored nor the level meter.
I run the main window at down to half screen height, so this is a major problem.
I am seeing the same issue in x86_64 and aarch64.

### PR DESCRIPTION
**Pull request by tmiw**
This resolves #610 by doing the following:

1. Forces the widths of all the boxes on the left hand side to be the same.
2. Changes main screen gauges from vertical to horizontal. (Additionally resolves #303.)
3. Rearranges boxes on main window to better utilize available space on shorter displays.

### CODE REVIEW

**Comment by Tyrbiter** [comment]
Not sure why, but seeing a build error now, didn't happen with my initial build of 1.9.6-devel:

/home/bdm/rpmbuild/BUILD/freedv-gui-1.9.6/src/rig_control/HamlibRigController.cpp: In static member function ‘static void HamlibRigController::InitializeHamlibLibrary()’:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.9.6/src/rig_control/HamlibRigController.cpp:127:26: error: invalid conversion from ‘int (*)(const rig_caps*, void*)’ to ‘int (*)(rig_caps*, void*)’ [-fpermissive]
  127 |         rig_list_foreach(&HamlibRigController::BuildRigList_, &RigList_);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          int (*)(const rig_caps*, void*)
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.9.6/src/rig_control/HamlibRigController.h:36,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.9.6/src/rig_control/HamlibRigController.cpp:31:
/usr/include/hamlib/rig.h:3686:18: note:   initializing argument 1 of ‘int rig_list_foreach(int (*)(rig_caps*, void*), void*)’
 3686 | rig_list_foreach HAMLIB_PARAMS((int (*cfunc)(struct rig_caps *, rig_ptr_t),
      |                  ^~~~~~~~~~~~~
gmake[2]: *** [src/rig_control/CMakeFiles/fdv_rig_control.dir/build.make:79: src/rig_control/CMakeFiles/fdv_rig_control.dir/HamlibRigController.cpp.o] Error 1
gmake[2]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.9.6/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:514: src/rig_control/CMakeFiles/fdv_rig_control.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

**Comment by Tyrbiter** [comment]
Looks like Mike changed some stuff in hamlib:

https://github.com/Hamlib/Hamlib/blob/master/include/hamlib/rig.h

**Comment by tmiw** [comment]
> Looks like Mike changed some stuff in hamlib:
> 
> https://github.com/Hamlib/Hamlib/blob/master/include/hamlib/rig.h

Unfortunately, fixing this for 4.6~git breaks it for 4.5.5. I'm very hesitant to force usage of the former given that it's not exactly stable. Let me see if I can detect 4.6 somehow during compile time.

**Comment by tmiw** [comment]
I created a Hamlib issue to see if we can get that reversed (or if Mike can recommend a workaround that will work on both 4.5 and 4.6).

**Comment by Tyrbiter** [comment]
OK, I now have a build of hamlib-4.6~git that contains Mike's fix.

When you have new code to test I will try it out.

**Comment by tmiw** [comment]
> OK, I now have a build of hamlib-4.6~git that contains Mike's fix.
> 
> When you have new code to test I will try it out.

https://github.com/drowe67/freedv-gui/pull/615, but I was able to check here on 4.5.5 and 4.6 and both worked fine with that change. Will merge into master as soon as GitHub finishes CI.

**Comment by Tyrbiter** [comment]
Now have a build with current code @tmiw, it is all looking very good.
