### PR TITLE
Refactor audio processing to use pipeline design pattern

### PR DESCRIPTION
**Pull request by tmiw**
Refactors audio processing (e.g. the logic inside the former `txProcessing()`/`rxProcessing()` functions) to use a pipeline design pattern. That is:

1. Each step required to process incoming audio and send it outbound is encapsulated into its own class (for example, `FreeDVTransmitStep`).
2. Required steps to perform RX and TX are encapsulated into `AudioPipeline`, which does the following for each step:
    1. If the audio from a previous step is at a different sample rate than what the current step expects, use a dynamically created `ResampleStep` object (which will be recreated if the expected sample rate ever changes) to resample to the expected rate.
    2. Execute the step and pass the output to the next step (or return the result to the caller).

The benefits of the above are as follows:

1. Ensures that every operation operates at the correct sample rate. For example, RX audio abnormalities in analog mode are still being occasionally encountered in multi-RX mode with the old logic which seem to be related to the equalizer processing inconsistent samples.
2. Easier testing of individual steps in the pipeline.
3. General logic simplification (e.g. `g_avmag` calculation can just assume sample rate = FS instead of checking/resampling first).
4. Additional steps can easily be added in the future if need be.
5. Sound device input/output sample rates can be decoupled, potentially removing the need to require both to be equal in audio settings (e.g. for Bluetooth devices with differing native sample rates for mic and speaker).

### CODE REVIEW

**Comment by tmiw** [comment]
@drowe67, once the GitHub action runs okay I'm going to merge this PR into #211 and generate new test builds with this code given how extensive the changes are. It seems to run okay for me (RX and TX) in brief tests but I could easily have missed something.

**Comment by Tyrbiter** [comment]
Hi @tmiw, I now see this when attempting to build using my previously working (for 1.8.0) Fedora rpm spec file:

In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/TxRxThread.cpp:93:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/../main.h:73:10: fatal error: lpcnet_freedv.h: No such file or directory
   73 | #include "lpcnet_freedv.h"
      |          ^~~~~~~~~~~~~~~~~

I can get a working binary using the build_linux.sh pulseaudio method, but I see that the main.h files have changed quite a bit. I have the lpcnet_freedv.h file installed from a -devel rpm but for whatever reason it's not being found by the compiler/linker.

Any thoughts? I presume that the pipeline/../main.h string above has somehow broken things.

**Comment by tmiw** [comment]
> Any thoughts? I presume that the pipeline/../main.h string above has somehow broken things.

Actually, only one file outside the pipeline folder seems to use it so I went ahead and moved that #include there. Let me know if that works any better for you. 👍

**Comment by Tyrbiter** [comment]
OK @tmiw, so that error seems to be gone but I now have this one:

In file included from /usr/include/wx-3.0/wx/intl.h:17,
                 from /usr/include/wx-3.0/wx/wx.h:22,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/../defines.h:24,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/TxRxThread.cpp:25:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/../topFrame.h:200:104: error: 'FREEDV_VERSION' was not declared in this scope
  200 |         TopFrame( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("FreeDV ") + _(FREEDV_VERSION), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(561,300 ), long style = wxDEFAULT_FRAME_STYLE|wxRESIZE_BORDER );
      |                                                                                                        ^~~~~~~~~~~~~~

which looks like a simple omission of a define?

**Comment by drowe67** [comment]
Hi @tmiw looks like a big change!  I'm pretty busy at the moment, and don't have the time to be involved in the review of such a big PR.  Also the C++ involved is a stretch for my limited C++ skills :slightly_smiling_face: 

So I'm happy for you to run with this one as you see fit.

One suggestion - some unit tests for the various classes that work outside of freedv-gui.  For example check they pass glitch free sine waves using automated tests. Very easy for subtle errors to creep in with resampling, these may be masked by the low quality coded speech.

**Comment by tmiw** [comment]
> OK @tmiw, so that error seems to be gone but I now have this one:
> 
> [ 60%] Built target fdv_audio In file included from /usr/include/wx-3.0/wx/intl.h:17, from /usr/include/wx-3.0/wx/wx.h:22, from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/../defines.h:24, from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/TxRxThread.cpp:25: /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/pipeline/../topFrame.h:200:104: error: 'FREEDV_VERSION' was not declared in this scope 200 | TopFrame( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("FreeDV ") + _(FREEDV_VERSION), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(561,300 ), long style = wxDEFAULT_FRAME_STYLE|wxRESIZE_BORDER ); | ^~~~~~~~~~~~~~
> 
> which looks like a simple omission of a define?

topFrame.h seems to properly include version.h (which defines `FREEDV_VERSION`) and the include paths in pipeline seem like they'd be correct based on the following in CMakeLists.txt:

```target_include_directories(fdv_audio_pipeline AFTER PRIVATE ${CODEC2_INCLUDE_DIRS} ${CMAKE_CURRENT_SOURCE_DIR}/.. ${CMAKE_CURRENT_BINARY_DIR}/..)```

(`CMAKE_CURRENT_SOURCE_DIR` would be src/pipeline and `CMAKE_CURRENT_BINARY_DIR` would be build_linux/src/pipeline here.)

Maybe do `rm -rf build_linux/*` and try a full cmake and rebuild?

> Hi @tmiw looks like a big change! I'm pretty busy at the moment, and don't have the time to be involved in the review of such a big PR. Also the C++ involved is a stretch for my limited C++ skills 🙂
> 
> So I'm happy for you to run with this one as you see fit.
> 
> One suggestion - some unit tests for the various classes that work outside of freedv-gui. For example check they pass glitch free sine waves using automated tests. Very easy for subtle errors to creep in with resampling, these may be masked by the low quality coded speech.

I'll have to think about how to do ctests for freedv-gui overall so they're not unwieldy to maintain. I did get a report of the voice keyer breaking with this change, though, so I'm going to take a look at that first.

**Comment by tmiw** [comment]
> Hope this adds more info.

Hmm, I'm not sure it should necessarily matter how cmake's getting run. I did move the reference to FREEDV_VERSION to main.cpp instead of topFrame.h, so hopefully that works better. If not, I'll see if I can duplicate this on Fedora.

**Comment by Tyrbiter** [comment]
> > Hope this adds more info.
> 
> Hmm, I'm not sure it should necessarily matter how cmake's getting run. I did move the reference to FREEDV_VERSION to main.cpp instead of topFrame.h, so hopefully that works better. If not, I'll see if I can duplicate this on Fedora.

OK, updated, ran build_linux.sh pulseaudio, then created a new tarball and ran rpmbuild, I now have new rpms built and installed. Will follow up if I see anything different in use.

**Comment by Tyrbiter** [comment]
Something that has been noticeable since the last 1.7.0 version I used is that the CPU use has increased quite a lot in 1.8.0-devel, at one point I had about 3-5% CPU in use with 1.7.0 whereas now I am seeing about 12-20% depending on analogue or digital selected, I never see the same reduction as before.

I'm using an 8 core 3GHz i7-9700 CPU, so essentially this is one whole core running freedv.

Thought it useful to mention this, not sure if this is unexpected.

**Comment by tmiw** [comment]
> Something that has been noticeable since the last 1.7.0 version I used is that the CPU use has increased quite a lot in 1.8.0-devel, at one point I had about 3-5% CPU in use with 1.7.0 whereas now I am seeing about 12-20% depending on analogue or digital selected, I never see the same reduction as before.
> 
> I'm using an 8 core 3GHz i7-9700 CPU, so essentially this is one whole core running freedv.
> 
> Thought it useful to mention this, not sure if this is unexpected.

It might be expected given that the number and/or order of the resamplers has changed. Personally I didn't really notice a difference on my system but I can investigate further once the bugs are quashed.

**Comment by tmiw** [comment]
> It might be expected given that the number and/or order of the resamplers has changed. Personally I didn't really notice a difference on my system but I can investigate further once the bugs are quashed.

To update, for me, it seems that the UI thread is still taking most of the CPU time (at least for RX). I suspect there's still a fair bit of room for optimization there as issues there have been reported before (e.g. #148). We'll save that for a future PR.

**Comment by Tyrbiter** [comment]
Those last two commits including https://github.com/drowe67/freedv-gui/pull/219/commits/3b7cefc06d3adf0d8b020db6e1c3ef8ea3be8b17 have reduced the CPU load. It is not constant but instead drops down to as low as 5% with peaks up at 17% and with values varying between these limits.

**Comment by tmiw** [comment]
FYI, current ctest results:

```
HT-TM05:build_osx mooneer$ make test
Running tests...
Test project /Users/mooneer/devel/freedv-gui/build_osx
    Start 1: pipeline_EitherOrTest
1/4 Test #1: pipeline_EitherOrTest ............   Passed    0.00 sec
    Start 2: pipeline_ExclusiveAccessTest
2/4 Test #2: pipeline_ExclusiveAccessTest .....   Passed    0.00 sec
    Start 3: pipeline_LevelAdjustTest
3/4 Test #3: pipeline_LevelAdjustTest .........   Passed    0.00 sec
    Start 4: pipeline_TapTest
4/4 Test #4: pipeline_TapTest .................   Passed    0.19 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =   0.20 sec
HT-TM05:build_osx mooneer$ 
```

**Comment by tmiw** [comment]
Current ctest results:

```
Running tests...
Test project /Users/mooneer/devel/freedv-gui/build_osx
    Start 1: pipeline_AudioPipelineTest
1/6 Test #1: pipeline_AudioPipelineTest .......   Passed    0.24 sec
    Start 2: pipeline_EitherOrTest
2/6 Test #2: pipeline_EitherOrTest ............   Passed    0.08 sec
    Start 3: pipeline_ExclusiveAccessTest
3/6 Test #3: pipeline_ExclusiveAccessTest .....   Passed    0.09 sec
    Start 4: pipeline_LevelAdjustTest
4/6 Test #4: pipeline_LevelAdjustTest .........   Passed    0.10 sec
    Start 5: pipeline_ResampleTest
5/6 Test #5: pipeline_ResampleTest ............   Passed    0.13 sec
    Start 6: pipeline_TapTest
6/6 Test #6: pipeline_TapTest .................   Passed    0.08 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) =   0.72 sec
```

The other ones seem to be FreeDV specific, so this is probably good for now.

**Comment by tmiw** [comment]
I'm doing another build. If I don't hear anything major within a few days, I'll merge this PR.
