### ISSUE TITLE
[Software Issue] FreeDV 2.0.1-dev does not build on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by jaspejavier** [drowe67/freedv-gui#913]
### Platform

Linux

### Platform Version

22.04.5 LTS

### FreeDV Version

2.0.1-dev-ed70

### Steps to Reproduce

Use `libwxgtk3.0-gtk3-dev` instead of `libwxgtk3.2-dev` (not in 22.04)
follow instructions until build_linux.sh

### Expected Behavior

Should build

### Actual Behavior

2 compile errors

### Additional Comments

Cause: there's no `libwxgtk3.2-dev` in 22.04 LTS, and using `libwxgtk3.0-gtk3-dev` instead causes 2 errors when running `./build_linux.sh`

Workaround: use backported `libwxgtk3.2-dev` from a ppa:

```
sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
sudo apt install libwxgtk3.2-dev

```
Using this workaround, FreeDV 2.0.1-dev compiles and runs with no apparent issue. Tested audio config, Tx Rx on RADEV1, Reporter.

Note 1: problably unrelated to the problem, but worth noting: using `python3.10-venv` instead of `python3.12-venv` (also, not in 22.04)
Note 2: FreeDV 1.9.9.2 was built in this same system with no issue.

When using `libwxgtk3.0-gtk3-dev` (the one available in 22.04) the compiler errors are:

First error:

```
/home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp: In lambda function:
/home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp:2203:64: error: cannot convert ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const char*’
 2203 |                 iter->second->userMessage = wxString::FromUTF8(message);
      |                                                                ^~~~~~~
      |                                                                |
      |                                                                const string {aka const std::__cxx11::basic_string<char>}
In file included from /usr/include/wx-3.0/wx/longlong.h:19,
                 from /usr/include/wx-3.0/wx/datetime.h:27,
                 from /home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp:23:
/usr/include/wx-3.0/wx/string.h:1742:42: note:   initializing argument 1 of ‘static wxString wxString::FromUTF8(const char*, size_t)’
 1742 |     static wxString FromUTF8(const char *utf8, size_t len = npos)
      |                              ~~~~~~~~~~~~^~~~
```

Possible solution:
libwxgtk 3.0 does not support const string as argument for FromUTF8. Converting to const char* solves this:

`iter->second->userMessage = wxString::FromUTF8(message.c_str());`

Second error:

```
/home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp: In constructor ‘FreeDVReporterDialog::FreeDVReporterDialog(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
/home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp:80:55: error: invalid new-expression of abstract class type ‘FreeDVReporterDialog::FreeDVReporterDataModel’
   80 |     spotsDataModel_ = new FreeDVReporterDataModel(this);
      |                                                       ^
In file included from /home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp:26:
/home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.h:149:16: note:   because the following virtual functions are pure within ‘FreeDVReporterDialog::FreeDVReporterDataModel’:
  149 |          class FreeDVReporterDataModel : public wxDataViewModel
      |                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.h:31,
                 from /home/javier/freedv-gui/src/gui/dialogs/freedv_reporter.cpp:26:
/usr/include/wx-3.0/wx/dataview.h:184:26: note:     ‘virtual unsigned int wxDataViewModel::GetColumnCount() const’
  184 |     virtual unsigned int GetColumnCount() const = 0;
      |                          ^~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/dataview.h:187:22: note:     ‘virtual wxString wxDataViewModel::GetColumnType(unsigned int) const’
  187 |     virtual wxString GetColumnType( unsigned int col ) const = 0;
      |                      ^~~~~~~~~~~~~

```
This one falls beyond my limited programming skills.

**Comment by tmiw** [comment]
Thanks for the report. Can you try the code in https://github.com/drowe67/freedv-gui/pull/914 and let me know if that works for you? It's able to compile on Mint 21, anyway (which also uses Ubuntu 22.04 as the base).

**Comment by jaspejavier** [comment]
Great! 

I confirm branch `ms-wxwidgets3.0-error` from #914 compiles and runs on Ubuntu 22.04.5 LTS using distro's available packages:

`libwxgtk3.0-gtk3-dev` instead of `libwxgtk3.2-dev`
`python3.10-venv` instead of `python3.12-venv`
`python3-numpy` instead of `python3-numpy-dev`

73 de LU3JIJ!

**Comment by tmiw** [comment]
Thanks for the testing! I went ahead and merged the fix, feel free to open another issue if needed.

**Comment by jaspejavier** [comment]
I confirm I built and run FreeDV 2.0.1-dev-1ef4 from scratch using branch master, just following normal instructions found in README on Ubuntu 22.04.5 LTS. Thanks!
