### ISSUE TITLE
[Software Issue] FreeDV fails to build with hamlib 4.6

### ISSUE THREAD

**Issue by gdt** [drowe67/freedv-gui#806]
### Platform

Other (not supported)

### Platform Version

NetBSD 10 amd64

### FreeDV Version

1.9.9.2

### Steps to Reproduce

Try to build the sources, with hamlib 4.6 installed.   Note that everything builds, except `src/hamlib.cpp`.

### Expected Behavior

Builds :-)  Less flippantly, a program should build with the most recent formal release of any dependency.  (Arguably, with any release that was current at any time in the year or 2 years before, when the release was made.)

### Actual Behavior

```
[  4%] Building CXX object src/CMakeFiles/freedv.dir/hamlib.cpp.o
/tmp/work/ham/freedv/work/freedv-gui-bb9558cc496b7b253fb54bb28486b0bcd7516ae5/src/hamlib.cpp: In constructor 'Hamlib::Hamlib()':
/tmp/work/ham/freedv/work/freedv-gui-bb9558cc496b7b253fb54bb28486b0bcd7516ae5/src/hamlib.cpp:44:22: error: invalid conversion from 'int (*)(const rig_caps*, void*)' to 'int (*)(rig_caps*, void*)' [-fpermissive]
   44 |     rig_list_foreach(build_list, &m_rigList);
      |                      ^~~~~~~~~~
      |                      |
      |                      int (*)(const rig_caps*, void*)
In file included from /tmp/work/ham/freedv/work/freedv-gui-bb9558cc496b7b253fb54bb28486b0bcd7516ae5/src/hamlib.h:8,
                 from /tmp/work/ham/freedv/work/freedv-gui-bb9558cc496b7b253fb54bb28486b0bcd7516ae5/src/hamlib.cpp:22:
/tmp/work/ham/freedv/work/.buildlink/include/hamlib/rig.h:3793:39: note:   initializing argument 1 of 'int rig_list_foreach(int (*)(rig_caps*, void*), void*)'
 3793 | rig_list_foreach HAMLIB_PARAMS((int (*cfunc)(struct rig_caps *, rig_ptr_t),
      |                                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/work/ham/freedv/work/.buildlink/include/hamlib/rig.h:113:33: note: in definition of macro 'HAMLIB_PARAMS'
  113 | #  define HAMLIB_PARAMS(protos) protos
      |                                 ^~~~~~
--- src/CMakeFiles/freedv.dir/hamlib.cpp.o ---
*** [src/CMakeFiles/freedv.dir/hamlib.cpp.o] Error code 1
```

### Additional Comments

I believe this is due to an intentional API change in hamlib, and that it's not that hard to fix.  Might be just dropping `const` from `struct rig_caps`.

73 de n1dam

**Comment by tmiw** [comment]
Are you able to try with the v2.0-dev branch on GitHub? That's where the most recent development has been taking place.

**Comment by gdt** [comment]
Not easily, as I have never gotten set up to build from source.   I can try to move the pkgsrc package (locally; doctrine is that we package releases) to the branch.

However, with this patch it builds.  I have not tested if it works,because getting set up for freedv is still on my todo list.  ( I did not find any tests hooked into cmake; pkgsrc can run those automatically.)  I'm just pasting the patch so it may not apply, but it is just dropping `const` from declaration and definition of the function passed to hamlib.

I suggest that if this fix is ok -- might need an ifdef for hamlib versions? -- that you release 1.9.9.3, so that packaging systems (including GNU/Linux distributions) have an easy upgrade even on stable branches.  I realize that's extra work, but hamlib's API break (if I understand correctly) is leading to this, and otherwise there is a risk that packaging systems will just mark freedv as broken.

```
--- src/hamlib.cpp.orig 2020-07-18 23:16:05.000000000 +0000
+++ src/hamlib.cpp
@@ -29,7 +29,7 @@ using namespace std;
 typedef std::vector<const struct rig_caps *> riglist_t;
 
 static bool rig_cmp(const struct rig_caps *rig1, const struct rig_caps *rig2);
-static int build_list(const struct rig_caps *rig, rig_ptr_t);
+static int build_list(struct rig_caps *rig, rig_ptr_t);
 
 Hamlib::Hamlib() : 
     m_rig(NULL),
@@ -55,7 +55,7 @@ Hamlib::~Hamlib() {
                close();
 }
 
-static int build_list(const struct rig_caps *rig, rig_ptr_t rigList) {
+static int build_list(struct rig_caps *rig, rig_ptr_t rigList) {
     ((riglist_t *)rigList)->push_back(rig); 
     return 1;
 }
```

**Comment by Tyrbiter** [comment]
I have been using hamlib-4.6~git and now hamlib-4.6 for over 18 months on Fedora 39/40/41 and I don't have any build problems with either freedv-1.9.9.2 or with the v2.0-dev branch.

I will confess to not having any experience with the BSD *nix variants.

One of the changes made in the new hamlib-4.7~git master branch is this:

https://github.com/Hamlib/Hamlib/commit/f2a9f091d08667db9d3fc2e842a427af7cfb990e

It may be similar or the same as your patch.

**Comment by gdt** [comment]
Thanks for pointing that out.

I don't think this is about BSD vs. not ( but am not 100% sure).  I think it's about a compiler warning about casting away const, and compilers vary how aggressively they do things like that.   So your system not warning, while useful in this case, doesn't argue that the code is ok.   Likewise, a warning is not proof of a type error, but this one seems to be right, when reading the code.

The hamlib commit is undoing the change in hamlib; my patch is mirroring the hamlib change.   Either way, the point is that the function signature of the callback passed to hamlib matches hamlib's callback signature declaration, AIUI.

**Comment by gdt** [comment]
I have asked for an immediate 4.6.1 on the hamlib developer list.

**Comment by tmiw** [comment]
Actually, I took a look at the patch and I just noticed that it may be on a much older version of the file. The Hamlib related logic in FreeDV 1.9.9.2 is located at https://github.com/drowe67/freedv-gui/blob/master/src/rig_control/HamlibRigController.cpp now, not hamlib.cpp. There also seems to already be logic in place to effectively handle this compile issue:

```c++
#if RIGCAPS_NOT_CONST
int HamlibRigController::BuildRigList_(struct rig_caps *rig, rig_ptr_t rigList) {
#else
int HamlibRigController::BuildRigList_(const struct rig_caps *rig, rig_ptr_t rigList) {    
#endif // RIGCAPS_NOT_CONST
```

Anyway, I'd double check to make sure the correct version is being downloaded and built.

**Comment by Tyrbiter** [comment]
You're right about this @tmiw , this conditional code is the reason that it works for me in the recent 1.9.x branch and v2.0-dev. freedv should be fine with whichever choice hamlib makes.

**Comment by gdt** [comment]
Indeed I am on an old version.   I now realize why, and 1.9.9.2 has a bunch of other issues.  Would you prefer freetel-codec2@ list, issues here, something else?    Will use issues absent advice/request.

Closing this as invalid, as I was not using 1.9.9.2.

**Comment by tmiw** [comment]
> Indeed I am on an old version. I now realize why, and 1.9.9.2 has a bunch of other issues. Would you prefer freetel-codec2@ list, issues here, something else? Will use issues absent advice/request.

Here is fine.
